version: '3.3'

services:
  db:
    build:
      dockerfile: ./db/Dockerfile
    container_name: 'db'
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: localuser
      POSTGRES_PASSWORD: cs4640LocalUser!
      POSTGRES_DB: example
      TZ: "America/New_York"
    volumes:
      - db-data:/var/lib/postgresql/data

  php:
    build:
      context: ./web/
      dockerfile: ./Dockerfile
    container_name: 'web'
    ports:
      - "8080:80"
    volumes:
      - ./web/src/:/opt/src/           # Maps your source code to a non-public directory
      - ./web/www/:/var/www/html/       # Maps your public web files (e.g., index.php, CSS, JS) to Apache's document root
      - ./web/log/:/opt/log/            # Logs directory
    depends_on:
      - db
    environment:
      TZ: "America/New_York"
      DB_HOST: db                       # Optional: Pass the DB service name as a host
      DB_PORT: 5432                     # Optional: Pass the DB port
      DB_USER: localuser                # Optional: Pass the DB user
      DB_PASS: cs4640LocalUser!         # Optional: Pass the DB password
      DB_NAME: example                  # Optional: Pass the DB name
volumes:
  db-data:
