version: '3.3'

services:
  db:
    build:
      dockerfile: ./db/Dockerfile
    container_name: 'db'
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: "America/New_York"
    volumes:
      - db-data:/var/lib/postgresql/data
  php:
    build:
      context: ./web/
      dockerfile: ./Dockerfile
    container_name: 'web'
    ports:
      - 8080:80
    volumes:
      - ./web/src/:/opt/src/pourpro
      - ./web/www/:/var/www/html/
      - ./web/cgi-bin/:/usr/lib/cgi-bin/
      - ./web/log/:/opt/log/
    depends_on:
      - db
    environment:
      TZ: "America/New_York"
      APP_ENV: "local"
      host: ${host}
      port: ${port}
      username: ${username}
      password: ${password}
      dbInstanceIdentifier: ${dbInstanceIdentifier}
volumes:
  db-data:
